// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211115052409_AddData")]
    partial class AddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Funcion", b =>
                {
                    b.Property<int>("FuncionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("FuncionId");

                    b.HasIndex("PeliculaId");

                    b.HasIndex("SalaId");

                    b.ToTable("Funciones");
                });

            modelBuilder.Entity("Domain.Entities.Pelicula", b =>
                {
                    b.Property<int>("PeliculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PeliculaId");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            PeliculaId = 1,
                            Poster = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/fast-and-furious-9-poster-1580411801.jpeg?crop=1xw:1xh;center,top&resize=980:*",
                            Sinopsis = "Dom Toretto lleva una vida tranquila con Letty y su hijo, el pequeño Brian, pero saben que el peligro siempre acecha. Su equipo pronto se une para detener un complot trascendental del asesino más hábil y el conductor de alto rendimiento el hermano de Dom.",
                            Titulo = "Rápidos y furiosos 9",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/ElLP7HAwUAw' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 2,
                            Poster = "https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SL1183_.jpg",
                            Sinopsis = "Después de los eventos devastadores de 'Avengers: Infinity War', el universo está en ruinas debido a las acciones de Thanos, el Titán Loco. Los Vengadores deberán reunirse para intentar restaurar el orden en el universo de una vez por todas.",
                            Titulo = "Avengers EndGame",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/znk2OICHbjY' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 3,
                            Poster = "https://terrigen-cdn-dev.marvel.com/content/prod/1x/snh_online_6072x9000_hero_03_opt.jpg",
                            Sinopsis = "La identidad de Spider-Man se revela a todos, ya no es capaz de separar su vida normal de los enormes riesgos que conlleva ser un Súper Héroe. Cuando pide ayuda a Doctor Strange, los riesgos pasan a ser aún más peligrosos.",
                            Titulo = "Spiderman: No way home",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/6QkTCmhOzuA' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 4,
                            Poster = "https://pics.filmaffinity.com/sonic_the_hedgehog-730493692-large.jpg",
                            Sinopsis = "El mundo necesitaba un héroe, tenía un erizo. Impulsado con una velocidad increíble, Sonic abraza su nuevo hogar en la Tierra, hasta que accidentalmente golpea la red eléctrica, lo que despierta la atención del genio malvado Dr. Robotnik.",
                            Titulo = "Sonic the hedgehog",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/Xb3E8eWZ1mk' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 5,
                            Poster = "https://pics.filmaffinity.com/luca-907827591-large.jpg",
                            Sinopsis = "Ambientada en una hermosa ciudad costera en la Riviera italiana, la película animada original es una historia sobre la mayoría de edad sobre un niño que experimenta un verano inolvidable lleno de helados, pasta e interminables paseos en scooter.",
                            Titulo = "Luca",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/_-8G-NSeZwo' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 6,
                            Poster = "https://es.web.img3.acsta.net/r_1920_1080/pictures/20/12/28/10/26/5942577.jpg",
                            Sinopsis = "Jim es un ex infante de marina que vive una vida solitaria como ranchero a lo largo de la frontera entre Arizona y México. Pero su existencia pacífica pronto se derrumba cuando intenta proteger a un niño que huye de los miembros de un cartel vicioso.",
                            Titulo = "The marksman",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/dpR5rte-96w' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 7,
                            Poster = "https://m.cinesargentinos.com.ar/poster/8898-el-rescate.jpg?1626438971",
                            Sinopsis = "Cuando el amor de su vida es secuestrado por terroristas para pedir un rescate, un héroe de guerra Brad Paxton corre contra el reloj para rescatar a la mujer que ama.",
                            Titulo = "El Rescate",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/BC2rFPNjnp0' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 8,
                            Poster = "https://imagenes.gatotv.com/categorias/peliculas/posters/infinite_2021.jpg",
                            Sinopsis = "Acosado por los recuerdos de lugares que nunca ha visitado, un hombre une fuerzas con un grupo de guerreros renacidos para evitar que un loco destruya el ciclo interminable de la vida y la reencarnación.",
                            Titulo = "Infinite",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/UKFjeglbNDg' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 9,
                            Poster = "https://m.media-amazon.com/images/I/51sWzqfPYEL._AC_.jpg",
                            Sinopsis = "En la conclusión de Matrix Reloaded, Neo daba otro paso hacia adelante en la búsqueda de la verdad que había empezado con su viaje al mundo real al comienzo de Matrix dejándole a la deriva en una tierra de nadie entre Matrix y el Mundo de las Máquinas.",
                            Titulo = "Matrix Revolutions",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/hMbexEPAOQI' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 10,
                            Poster = "https://pics.filmaffinity.com/tom_and_jerry-740894888-large.jpg",
                            Sinopsis = "Una rivalidad legendaria resurge cuando Jerry se muda al mejor hotel de la ciudad de Nueva York en vísperas de la boda del siglo, lo que obliga al desesperado planificador de eventos a contratar a Tom para deshacerse de él.",
                            Titulo = "Tom y jerry",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/ZJVb-IR1Jnw' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 11,
                            Poster = "https://pics.filmaffinity.com/godzilla_vs_kong-370227109-large.jpg",
                            Sinopsis = "Godzilla y Kong, dos de las fuerzas más poderosas de un planeta habitado por todo tipo de aterradoras criaturas, se enfrentan en un espectacular combate que sacude los cimientos de la humanidad.",
                            Titulo = "Godzilla vs. Kong",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/Kqg8zLgESyQ' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 12,
                            Poster = "https://image.tmdb.org/t/p/original//i6E8fx8lAEI0PGGCUlaA2Ap1gWi.jpg",
                            Sinopsis = "La superestrella LeBron James y su hijo pequeño, Dom, quedan atrapados en el espacio digital por una IA rebelde. LeBron se une a Bugs Bunny, Daffy Duck y el resto de la pandilla Looney Tunes para un juego de baloncesto de alto riesgo.",
                            Titulo = "Space Jam: una nueva era",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/8GltZA7F7-M' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 13,
                            Poster = "https://pics.filmaffinity.com/paw_patrol_the_movie-626479283-large.jpg",
                            Sinopsis = "La Patrulla Canina está en racha. Cuando Humdinger, su mayor rival, se convierte en alcalde de la cercana Ciudad Aventura y empieza a causar estragos, Ryder y los heroicos cachorros se ponen en marcha para enfrentarse a este nuevo desafío.",
                            Titulo = "La Patrulla Canina: La película",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/ABjdw_caRsQ' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 14,
                            Poster = "https://pics.filmaffinity.com/nobody-390795243-large.jpg",
                            Sinopsis = "Hutch Mansell no se defiende cuando dos ladrones irrumpen en su casa. En un aluvión de puños, disparos y chirridos de neumáticos, Hutch ahora debe salvar a su esposa e hijo de un adversario peligroso y asegurarse de que nunca más lo subestimen.",
                            Titulo = "Nadie",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/Mzrib73dVbc' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 15,
                            Poster = "https://pics.filmaffinity.com/the_unholy-403969644-large.jpg",
                            Sinopsis = "Un periodista en horas bajas descubre una serie de aparentes milagros de una joven que dice haber sido visitada por la Virgen María, milagros acaecidos en un pequeño pueblo de Nueva Inglaterra.",
                            Titulo = "Ruega por nosotros",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/a_BYIlWcbVg' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 16,
                            Poster = "https://static.cinemarkhoyts.com.ar/Images/Posters/3fc8caad36d4f72651d8068bfa039110.jpg?v=08112021",
                            Sinopsis = "Una Alerta Roja emitida por Interpol es una alerta global para cazar y capturar a los más buscados del mundo. Pero cuando un atrevido atraco reúne al principal agente del FBI (Johnson) y dos criminales rivales (Gadot, Reynolds), no se sabe qué sucederá.",
                            Titulo = "Alerta roja",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/FojI-_1hST4' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 17,
                            Poster = "https://image.tmdb.org/t/p/original//hKZHk6I1p58ZeXbwjQok7DSWfZ.jpg",
                            Sinopsis = "Una joven desesperada recurre a una clínica que hace abortos clandestinos. Al descubrir que está en su cuarto mes de embarazo, la doctora se niega, pero le propone vender el bebé a unos clientes suyos.",
                            Titulo = "El Apego",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/80P35D4vyHg' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 18,
                            Poster = "https://images.clarin.com/2021/04/16/el-primer-afiche-que-se___8xbNrbH6m_720x0__1.jpg",
                            Sinopsis = "Los Eternos, una raza de seres inmortales con poderes sobrehumanos que han vivido en secreto en la Tierra durante miles de años, se reúnen para luchar contra los malvados Deviants.",
                            Titulo = "Eternals",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/v1EkoQV4g5c' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 19,
                            Poster = "https://static.cinemarkhoyts.com.ar/Images/Posters/1fa377f4d4d78239363a228dd91ea241.jpg?v=01112021",
                            Sinopsis = "Chernobyl es el primer largometraje ruso importante sobre las consecuencias de la explosión en la central nuclear de Chernobyl, cuando cientos de personas sacrificaron sus vidas para limpiar el lugar de la catástrofe.",
                            Titulo = "Chernóbil: La Película",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/9DkXQM3eR8I' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        },
                        new
                        {
                            PeliculaId = 20,
                            Poster = "https://pics.filmaffinity.com/venom_let_there_be_carnage-797643212-large.jpg",
                            Sinopsis = "Regresa Eddie Brock y su Venom. Que en esta oportunidad se reencontrará con Cletus Cassady,el enemigo más sangriento de la historia de Spiderman a quién se lo conoce como “Carnage”.",
                            Titulo = "Venom: Carnage Liberado",
                            Trailer = "<iframe width='660' height='315' src='https://www.youtube.com/embed/F4Ygcigj0Gk' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.HasKey("SalaId");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaId = 1,
                            Capacidad = 5
                        },
                        new
                        {
                            SalaId = 2,
                            Capacidad = 15
                        },
                        new
                        {
                            SalaId = 3,
                            Capacidad = 35
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FuncionId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId", "FuncionId");

                    b.HasIndex("FuncionId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Funcion", b =>
                {
                    b.HasOne("Domain.Entities.Pelicula", "Peliculas")
                        .WithMany("Funciones")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sala", "Salas")
                        .WithMany("Funciones")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peliculas");

                    b.Navigation("Salas");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.Funcion", "Funciones")
                        .WithMany("Tickets")
                        .HasForeignKey("FuncionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("Domain.Entities.Funcion", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Pelicula", b =>
                {
                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("Domain.Entities.Sala", b =>
                {
                    b.Navigation("Funciones");
                });
#pragma warning restore 612, 618
        }
    }
}
